### PR TITLE
Add audio configuration for Windows

### PR DESCRIPTION
**Pull request by jbonhag**
Add the customize command to get audio working on Windows

### CODE REVIEW

**Comment by jbonhag** [comment]
Hey!  I wasn't sure where to put this, but I wanted to document it somewhere.

**Comment by GeoffreyPlitt** [comment]
Cool. Why don't you add some if/then branching based on detecting the current OS, so it works on all systems? Then I'll merge this.

http://stackoverflow.com/questions/11784109/detecting-operating-systems-in-ruby

**Comment by jbonhag** [comment]
Do you think it's safe to use `RUBY_PLATFORM` instead of `RbConfig::CONFIG['host_os']`?  Does Vagrant ever run on JRuby?

**Comment by GeoffreyPlitt** [comment]
Sounds fine to me. I don't know Ruby well.

**Comment by jbonhag** [comment]
Sounds good on Mac, I'll test Windows tomorrow.

**Comment by jbonhag** [comment]
Welp, that took forever, but I finally tested it on Windows and it sounds good.

**Comment by GeoffreyPlitt** [comment]
Awesome, thanks!

**Pull request merged**
